/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkspaceRouteImport } from './routes/workspace'
import { Route as TryRouteImport } from './routes/try'
import { Route as ThankYouRouteImport } from './routes/thank-you'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SubscribeRouteImport } from './routes/subscribe'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PreviewRouteImport } from './routes/preview'
import { Route as Plan30RouteImport } from './routes/plan-30'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IntegrationsRouteImport } from './routes/integrations'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as CalculatorRouteImport } from './routes/calculator'
import { Route as AnalyzeRouteImport } from './routes/analyze'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiGenerateImageRouteImport } from './routes/api/generate-image'
import { Route as AdminDomainsRouteImport } from './routes/admin.domains'
import { Route as ApiPublicRefreshCompetitorsRouteImport } from './routes/api/public/refresh-competitors'
import { Route as ApiPublicRefreshAnalysesRouteImport } from './routes/api/public/refresh-analyses'
import { Route as AdminCustomerEmailRouteImport } from './routes/admin.customer.$email'

const WorkspaceRoute = WorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const TryRoute = TryRouteImport.update({
  id: '/try',
  path: '/try',
  getParentRoute: () => rootRouteImport,
} as any)
const ThankYouRoute = ThankYouRouteImport.update({
  id: '/thank-you',
  path: '/thank-you',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscribeRoute = SubscribeRouteImport.update({
  id: '/subscribe',
  path: '/subscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewRoute = PreviewRouteImport.update({
  id: '/preview',
  path: '/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const Plan30Route = Plan30RouteImport.update({
  id: '/plan-30',
  path: '/plan-30',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsRoute = IntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorRoute = CalculatorRouteImport.update({
  id: '/calculator',
  path: '/calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyzeRoute = AnalyzeRouteImport.update({
  id: '/analyze',
  path: '/analyze',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateImageRoute = ApiGenerateImageRouteImport.update({
  id: '/api/generate-image',
  path: '/api/generate-image',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDomainsRoute = AdminDomainsRouteImport.update({
  id: '/domains',
  path: '/domains',
  getParentRoute: () => AdminRoute,
} as any)
const ApiPublicRefreshCompetitorsRoute =
  ApiPublicRefreshCompetitorsRouteImport.update({
    id: '/api/public/refresh-competitors',
    path: '/api/public/refresh-competitors',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicRefreshAnalysesRoute =
  ApiPublicRefreshAnalysesRouteImport.update({
    id: '/api/public/refresh-analyses',
    path: '/api/public/refresh-analyses',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminCustomerEmailRoute = AdminCustomerEmailRouteImport.update({
  id: '/customer/$email',
  path: '/customer/$email',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/analyze': typeof AnalyzeRoute
  '/calculator': typeof CalculatorRoute
  '/faq': typeof FaqRoute
  '/how-it-works': typeof HowItWorksRoute
  '/integrations': typeof IntegrationsRoute
  '/login': typeof LoginRoute
  '/plan-30': typeof Plan30Route
  '/preview': typeof PreviewRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/subscribe': typeof SubscribeRoute
  '/terms': typeof TermsRoute
  '/thank-you': typeof ThankYouRoute
  '/try': typeof TryRoute
  '/workspace': typeof WorkspaceRoute
  '/admin/domains': typeof AdminDomainsRoute
  '/api/generate-image': typeof ApiGenerateImageRoute
  '/admin/customer/$email': typeof AdminCustomerEmailRoute
  '/api/public/refresh-analyses': typeof ApiPublicRefreshAnalysesRoute
  '/api/public/refresh-competitors': typeof ApiPublicRefreshCompetitorsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/analyze': typeof AnalyzeRoute
  '/calculator': typeof CalculatorRoute
  '/faq': typeof FaqRoute
  '/how-it-works': typeof HowItWorksRoute
  '/integrations': typeof IntegrationsRoute
  '/login': typeof LoginRoute
  '/plan-30': typeof Plan30Route
  '/preview': typeof PreviewRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/subscribe': typeof SubscribeRoute
  '/terms': typeof TermsRoute
  '/thank-you': typeof ThankYouRoute
  '/try': typeof TryRoute
  '/workspace': typeof WorkspaceRoute
  '/admin/domains': typeof AdminDomainsRoute
  '/api/generate-image': typeof ApiGenerateImageRoute
  '/admin/customer/$email': typeof AdminCustomerEmailRoute
  '/api/public/refresh-analyses': typeof ApiPublicRefreshAnalysesRoute
  '/api/public/refresh-competitors': typeof ApiPublicRefreshCompetitorsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/analyze': typeof AnalyzeRoute
  '/calculator': typeof CalculatorRoute
  '/faq': typeof FaqRoute
  '/how-it-works': typeof HowItWorksRoute
  '/integrations': typeof IntegrationsRoute
  '/login': typeof LoginRoute
  '/plan-30': typeof Plan30Route
  '/preview': typeof PreviewRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/subscribe': typeof SubscribeRoute
  '/terms': typeof TermsRoute
  '/thank-you': typeof ThankYouRoute
  '/try': typeof TryRoute
  '/workspace': typeof WorkspaceRoute
  '/admin/domains': typeof AdminDomainsRoute
  '/api/generate-image': typeof ApiGenerateImageRoute
  '/admin/customer/$email': typeof AdminCustomerEmailRoute
  '/api/public/refresh-analyses': typeof ApiPublicRefreshAnalysesRoute
  '/api/public/refresh-competitors': typeof ApiPublicRefreshCompetitorsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/analyze'
    | '/calculator'
    | '/faq'
    | '/how-it-works'
    | '/integrations'
    | '/login'
    | '/plan-30'
    | '/preview'
    | '/pricing'
    | '/privacy'
    | '/sitemap.xml'
    | '/subscribe'
    | '/terms'
    | '/thank-you'
    | '/try'
    | '/workspace'
    | '/admin/domains'
    | '/api/generate-image'
    | '/admin/customer/$email'
    | '/api/public/refresh-analyses'
    | '/api/public/refresh-competitors'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/analyze'
    | '/calculator'
    | '/faq'
    | '/how-it-works'
    | '/integrations'
    | '/login'
    | '/plan-30'
    | '/preview'
    | '/pricing'
    | '/privacy'
    | '/sitemap.xml'
    | '/subscribe'
    | '/terms'
    | '/thank-you'
    | '/try'
    | '/workspace'
    | '/admin/domains'
    | '/api/generate-image'
    | '/admin/customer/$email'
    | '/api/public/refresh-analyses'
    | '/api/public/refresh-competitors'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/analyze'
    | '/calculator'
    | '/faq'
    | '/how-it-works'
    | '/integrations'
    | '/login'
    | '/plan-30'
    | '/preview'
    | '/pricing'
    | '/privacy'
    | '/sitemap.xml'
    | '/subscribe'
    | '/terms'
    | '/thank-you'
    | '/try'
    | '/workspace'
    | '/admin/domains'
    | '/api/generate-image'
    | '/admin/customer/$email'
    | '/api/public/refresh-analyses'
    | '/api/public/refresh-competitors'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AnalyzeRoute: typeof AnalyzeRoute
  CalculatorRoute: typeof CalculatorRoute
  FaqRoute: typeof FaqRoute
  HowItWorksRoute: typeof HowItWorksRoute
  IntegrationsRoute: typeof IntegrationsRoute
  LoginRoute: typeof LoginRoute
  Plan30Route: typeof Plan30Route
  PreviewRoute: typeof PreviewRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SubscribeRoute: typeof SubscribeRoute
  TermsRoute: typeof TermsRoute
  ThankYouRoute: typeof ThankYouRoute
  TryRoute: typeof TryRoute
  WorkspaceRoute: typeof WorkspaceRoute
  ApiGenerateImageRoute: typeof ApiGenerateImageRoute
  ApiPublicRefreshAnalysesRoute: typeof ApiPublicRefreshAnalysesRoute
  ApiPublicRefreshCompetitorsRoute: typeof ApiPublicRefreshCompetitorsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workspace': {
      id: '/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof WorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/try': {
      id: '/try'
      path: '/try'
      fullPath: '/try'
      preLoaderRoute: typeof TryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thank-you': {
      id: '/thank-you'
      path: '/thank-you'
      fullPath: '/thank-you'
      preLoaderRoute: typeof ThankYouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscribe': {
      id: '/subscribe'
      path: '/subscribe'
      fullPath: '/subscribe'
      preLoaderRoute: typeof SubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview': {
      id: '/preview'
      path: '/preview'
      fullPath: '/preview'
      preLoaderRoute: typeof PreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan-30': {
      id: '/plan-30'
      path: '/plan-30'
      fullPath: '/plan-30'
      preLoaderRoute: typeof Plan30RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations': {
      id: '/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof IntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculator': {
      id: '/calculator'
      path: '/calculator'
      fullPath: '/calculator'
      preLoaderRoute: typeof CalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analyze': {
      id: '/analyze'
      path: '/analyze'
      fullPath: '/analyze'
      preLoaderRoute: typeof AnalyzeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-image': {
      id: '/api/generate-image'
      path: '/api/generate-image'
      fullPath: '/api/generate-image'
      preLoaderRoute: typeof ApiGenerateImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/domains': {
      id: '/admin/domains'
      path: '/domains'
      fullPath: '/admin/domains'
      preLoaderRoute: typeof AdminDomainsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/public/refresh-competitors': {
      id: '/api/public/refresh-competitors'
      path: '/api/public/refresh-competitors'
      fullPath: '/api/public/refresh-competitors'
      preLoaderRoute: typeof ApiPublicRefreshCompetitorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/refresh-analyses': {
      id: '/api/public/refresh-analyses'
      path: '/api/public/refresh-analyses'
      fullPath: '/api/public/refresh-analyses'
      preLoaderRoute: typeof ApiPublicRefreshAnalysesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/customer/$email': {
      id: '/admin/customer/$email'
      path: '/customer/$email'
      fullPath: '/admin/customer/$email'
      preLoaderRoute: typeof AdminCustomerEmailRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminDomainsRoute: typeof AdminDomainsRoute
  AdminCustomerEmailRoute: typeof AdminCustomerEmailRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminDomainsRoute: AdminDomainsRoute,
  AdminCustomerEmailRoute: AdminCustomerEmailRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AnalyzeRoute: AnalyzeRoute,
  CalculatorRoute: CalculatorRoute,
  FaqRoute: FaqRoute,
  HowItWorksRoute: HowItWorksRoute,
  IntegrationsRoute: IntegrationsRoute,
  LoginRoute: LoginRoute,
  Plan30Route: Plan30Route,
  PreviewRoute: PreviewRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SubscribeRoute: SubscribeRoute,
  TermsRoute: TermsRoute,
  ThankYouRoute: ThankYouRoute,
  TryRoute: TryRoute,
  WorkspaceRoute: WorkspaceRoute,
  ApiGenerateImageRoute: ApiGenerateImageRoute,
  ApiPublicRefreshAnalysesRoute: ApiPublicRefreshAnalysesRoute,
  ApiPublicRefreshCompetitorsRoute: ApiPublicRefreshCompetitorsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
