/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkspaceRouteImport } from './routes/workspace'
import { Route as TryRouteImport } from './routes/try'
import { Route as ThankYouRouteImport } from './routes/thank-you'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SubscribeRouteImport } from './routes/subscribe'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AnalyzeRouteImport } from './routes/analyze'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiGenerateImageRouteImport } from './routes/api/generate-image'
import { Route as ApiPublicRefreshAnalysesRouteImport } from './routes/api/public/refresh-analyses'

const WorkspaceRoute = WorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const TryRoute = TryRouteImport.update({
  id: '/try',
  path: '/try',
  getParentRoute: () => rootRouteImport,
} as any)
const ThankYouRoute = ThankYouRouteImport.update({
  id: '/thank-you',
  path: '/thank-you',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscribeRoute = SubscribeRouteImport.update({
  id: '/subscribe',
  path: '/subscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyzeRoute = AnalyzeRouteImport.update({
  id: '/analyze',
  path: '/analyze',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateImageRoute = ApiGenerateImageRouteImport.update({
  id: '/api/generate-image',
  path: '/api/generate-image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRefreshAnalysesRoute =
  ApiPublicRefreshAnalysesRouteImport.update({
    id: '/api/public/refresh-analyses',
    path: '/api/public/refresh-analyses',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/analyze': typeof AnalyzeRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/subscribe': typeof SubscribeRoute
  '/terms': typeof TermsRoute
  '/thank-you': typeof ThankYouRoute
  '/try': typeof TryRoute
  '/workspace': typeof WorkspaceRoute
  '/api/generate-image': typeof ApiGenerateImageRoute
  '/api/public/refresh-analyses': typeof ApiPublicRefreshAnalysesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/analyze': typeof AnalyzeRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/subscribe': typeof SubscribeRoute
  '/terms': typeof TermsRoute
  '/thank-you': typeof ThankYouRoute
  '/try': typeof TryRoute
  '/workspace': typeof WorkspaceRoute
  '/api/generate-image': typeof ApiGenerateImageRoute
  '/api/public/refresh-analyses': typeof ApiPublicRefreshAnalysesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/analyze': typeof AnalyzeRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/subscribe': typeof SubscribeRoute
  '/terms': typeof TermsRoute
  '/thank-you': typeof ThankYouRoute
  '/try': typeof TryRoute
  '/workspace': typeof WorkspaceRoute
  '/api/generate-image': typeof ApiGenerateImageRoute
  '/api/public/refresh-analyses': typeof ApiPublicRefreshAnalysesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/analyze'
    | '/login'
    | '/privacy'
    | '/subscribe'
    | '/terms'
    | '/thank-you'
    | '/try'
    | '/workspace'
    | '/api/generate-image'
    | '/api/public/refresh-analyses'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/analyze'
    | '/login'
    | '/privacy'
    | '/subscribe'
    | '/terms'
    | '/thank-you'
    | '/try'
    | '/workspace'
    | '/api/generate-image'
    | '/api/public/refresh-analyses'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/analyze'
    | '/login'
    | '/privacy'
    | '/subscribe'
    | '/terms'
    | '/thank-you'
    | '/try'
    | '/workspace'
    | '/api/generate-image'
    | '/api/public/refresh-analyses'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AnalyzeRoute: typeof AnalyzeRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  SubscribeRoute: typeof SubscribeRoute
  TermsRoute: typeof TermsRoute
  ThankYouRoute: typeof ThankYouRoute
  TryRoute: typeof TryRoute
  WorkspaceRoute: typeof WorkspaceRoute
  ApiGenerateImageRoute: typeof ApiGenerateImageRoute
  ApiPublicRefreshAnalysesRoute: typeof ApiPublicRefreshAnalysesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workspace': {
      id: '/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof WorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/try': {
      id: '/try'
      path: '/try'
      fullPath: '/try'
      preLoaderRoute: typeof TryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thank-you': {
      id: '/thank-you'
      path: '/thank-you'
      fullPath: '/thank-you'
      preLoaderRoute: typeof ThankYouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscribe': {
      id: '/subscribe'
      path: '/subscribe'
      fullPath: '/subscribe'
      preLoaderRoute: typeof SubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analyze': {
      id: '/analyze'
      path: '/analyze'
      fullPath: '/analyze'
      preLoaderRoute: typeof AnalyzeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-image': {
      id: '/api/generate-image'
      path: '/api/generate-image'
      fullPath: '/api/generate-image'
      preLoaderRoute: typeof ApiGenerateImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/refresh-analyses': {
      id: '/api/public/refresh-analyses'
      path: '/api/public/refresh-analyses'
      fullPath: '/api/public/refresh-analyses'
      preLoaderRoute: typeof ApiPublicRefreshAnalysesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AnalyzeRoute: AnalyzeRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  SubscribeRoute: SubscribeRoute,
  TermsRoute: TermsRoute,
  ThankYouRoute: ThankYouRoute,
  TryRoute: TryRoute,
  WorkspaceRoute: WorkspaceRoute,
  ApiGenerateImageRoute: ApiGenerateImageRoute,
  ApiPublicRefreshAnalysesRoute: ApiPublicRefreshAnalysesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
